# Generated by Django 2.2.6 on 2019-12-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('post', models.CharField(choices=[('Ex Mem', 'Executive Member'), ('Joint', 'Joint Secretary'), ('Additional', 'Additional Secretary'), ('General', 'General Secretary')], default='Ex Mem', max_length=50)),
            ],
        ),
    ]
